apiVersion : apps/v1
kind: Deployment
metadata:
  name: nikitkubtcldemo 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nikitkubtcldemo
  template:
    metadata:
      labels:
        app: nikitkubtcldemo 
    spec:
      containers:
        - name: nikitkubtcldemo 
          image: myacrddemo.azurecr.io/nikitkubtcldemo
          ports:
          - containerPort: 2020